# Generated by Django 5.1.1 on 2024-10-10 03:23

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageId', models.TextField(default=core.models.generateTagIds)),
                ('sentDate', models.DateTimeField(auto_now_add=True)),
                ('senderTag', models.TextField()),
                ('messageContents', models.TextField()),
                ('messageReceivers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.TextField(default=core.models.generateTagIds)),
                ('registeredDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('studentName', models.TextField()),
                ('studentContact', models.TextField()),
                ('studentRegno', models.TextField()),
                ('studentFaculty', models.TextField()),
                ('studentProgramme', models.TextField()),
                ('studentResidence', models.TextField()),
                ('studentAccomodation', models.TextField()),
                ('attachedStudent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-registeredDate',),
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField(default=core.models.generateTagIds)),
                ('userTag', models.IntegerField(default=0)),
                ('attachedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
